"""Removed Examination Table

Revision ID: 08c16ed3a707
Revises: 6d6880f9bc1e
Create Date: 2026-05-25 10:36:57.757771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08c16ed3a707'
down_revision: Union[str, Sequence[str], None] = '6d6880f9bc1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExaminationSlotTable', sa.Column('examination_date', sa.Date(), nullable=False))
    op.add_column('ExaminationSlotTable', sa.Column('examination_type', postgresql.ENUM('ASSESMENT', 'REASSESMENT', name='examinationtype', create_type=False), nullable=True))
    op.create_index(op.f('ix_ExaminationSlotTable_examination_date'), 'ExaminationSlotTable', ['examination_date'], unique=False)
    op.drop_constraint(op.f('ExaminationSlotTable_examination_id_fkey'), 'ExaminationSlotTable', type_='foreignkey')
    op.drop_column('ExaminationSlotTable', 'examination_id')
    op.drop_column('ExaminationTable', 'examination_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExaminationTable', sa.Column('examination_type', postgresql.ENUM('ASSESMENT', 'REASSESMENT', name='examinationtype', create_type=False), autoincrement=False, nullable=True))
    op.add_column('ExaminationSlotTable', sa.Column('examination_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('ExaminationSlotTable_examination_id_fkey'), 'ExaminationSlotTable', 'ExaminationTable', ['examination_id'], ['examination_id'])
    op.drop_index(op.f('ix_ExaminationSlotTable_examination_date'), table_name='ExaminationSlotTable')
    op.drop_column('ExaminationSlotTable', 'examination_type')
    op.drop_column('ExaminationSlotTable', 'examination_date')
    # ### end Alembic commands ###
