"""Made The Name Changes in the User Table

Revision ID: 2aa97f43a5b7
Revises: a10512e7f59f
Create Date: 2026-05-20 11:00:09.027409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa97f43a5b7'
down_revision: Union[str, Sequence[str], None] = 'a10512e7f59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_Table', sa.Column('user_first_name', sa.String(), nullable=False))
    op.add_column('User_Table', sa.Column('user_last_name', sa.String(), nullable=False))
    op.drop_column('User_Table', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_Table', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('User_Table', 'user_last_name')
    op.drop_column('User_Table', 'user_first_name')
    # ### end Alembic commands ###
