"""Modified User and User Role Table

Revision ID: 2e904bc3e04a
Revises: 4776bcc01771
Create Date: 2026-05-22 10:38:04.442733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e904bc3e04a'
down_revision: Union[str, Sequence[str], None] = '4776bcc01771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('INCOMPLETE', 'PUNCTUAL', 'DELAYED', 'DANGEROUSLY_DELAYED', name='mocstatus').create(op.get_bind())
    sa.Enum('COMPLETED', 'PENDING', 'REFUNDED', name='paymentstatus').create(op.get_bind())
    sa.Enum('PENDING', 'SCHEDULED', 'COMPLETED', name='userexaminationstatus').create(op.get_bind())
    sa.Enum('ASSESMENT', 'REASSESMENT', name='examinationtype').create(op.get_bind())
    sa.Enum('INCOMPLETE', 'COMPLETED', name='processstatus').create(op.get_bind())
    sa.Enum('ACTIVE', 'INACTIVE', 'LOST', name='certificationstatus').create(op.get_bind())
    op.create_table('ExaminationTable',
    sa.Column('examination_id', sa.UUID(), nullable=False),
    sa.Column('examination_date', sa.Date(), nullable=False),
    sa.Column('examination_type', postgresql.ENUM('ASSESMENT', 'REASSESMENT', name='examinationtype', create_type=False), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('examination_id')
    )
    op.create_index(op.f('ix_ExaminationTable_created_by'), 'ExaminationTable', ['created_by'], unique=False)
    op.create_index(op.f('ix_ExaminationTable_examination_date'), 'ExaminationTable', ['examination_date'], unique=False)
    op.create_index(op.f('ix_ExaminationTable_examination_id'), 'ExaminationTable', ['examination_id'], unique=False)
    op.create_table('UserTable',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_title', postgresql.ENUM('Mr', 'Ms', 'Dr', 'Mrs', name='usertitle', create_type=False), nullable=True),
    sa.Column('user_first_name', sa.String(), nullable=False),
    sa.Column('user_last_name', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_password', sa.String(), nullable=False),
    sa.Column('user_degree', sa.String(), nullable=True),
    sa.Column('user_certificate', sa.String(), nullable=True),
    sa.Column('user_passing_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_UserTable_user_email'), 'UserTable', ['user_email'], unique=False)
    op.create_table('CertificationTable',
    sa.Column('certification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('certification_status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'LOST', name='certificationstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserTable.user_id'], ),
    sa.PrimaryKeyConstraint('certification_id')
    )
    op.create_index(op.f('ix_CertificationTable_certification_id'), 'CertificationTable', ['certification_id'], unique=False)
    op.create_index(op.f('ix_CertificationTable_user_id'), 'CertificationTable', ['user_id'], unique=False)
    op.create_table('CycleTable',
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserTable.user_id'], ),
    sa.PrimaryKeyConstraint('cycle_id')
    )
    op.create_index(op.f('ix_CycleTable_cycle_id'), 'CycleTable', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_CycleTable_end_date'), 'CycleTable', ['end_date'], unique=False)
    op.create_index(op.f('ix_CycleTable_start_date'), 'CycleTable', ['start_date'], unique=False)
    op.create_table('ExaminationSlotTable',
    sa.Column('examination_slot_id', sa.UUID(), nullable=False),
    sa.Column('examination_id', sa.UUID(), nullable=True),
    sa.Column('examination_slot_start_time', sa.Time(), nullable=False),
    sa.Column('examination_slot_end_time', sa.Time(), nullable=False),
    sa.Column('examination_slot_total_capacity', sa.Integer(), nullable=False),
    sa.Column('examination_slot_available_capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['examination_id'], ['ExaminationTable.examination_id'], ),
    sa.PrimaryKeyConstraint('examination_slot_id')
    )
    op.create_table('UserRoleTable',
    sa.Column('userrole_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_role', postgresql.ENUM('ADMIN', 'SUPERADMIN', 'USER', 'CANDIDATE', 'DIPLOMATE', name='userrole', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['UserTable.user_id'], ),
    sa.PrimaryKeyConstraint('userrole_id')
    )
    op.create_table('MocTable',
    sa.Column('moc_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=True),
    sa.Column('moc_status', postgresql.ENUM('INCOMPLETE', 'PUNCTUAL', 'DELAYED', 'DANGEROUSLY_DELAYED', name='mocstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['CycleTable.cycle_id'], ),
    sa.PrimaryKeyConstraint('moc_id')
    )
    op.create_index(op.f('ix_MocTable_moc_id'), 'MocTable', ['moc_id'], unique=False)
    op.create_table('UserExaminationSlotTable',
    sa.Column('user_examination_slot_id', sa.UUID(), nullable=False),
    sa.Column('examination_slot_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_examination_status', postgresql.ENUM('PENDING', 'SCHEDULED', 'COMPLETED', name='userexaminationstatus', create_type=False), nullable=False),
    sa.Column('payment_status', postgresql.ENUM('COMPLETED', 'PENDING', 'REFUNDED', name='paymentstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['examination_slot_id'], ['ExaminationSlotTable.examination_slot_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['UserTable.user_id'], ),
    sa.PrimaryKeyConstraint('user_examination_slot_id')
    )
    op.create_table('ContinuousLearningTable',
    sa.Column('cl_id', sa.UUID(), nullable=False),
    sa.Column('moc_id', sa.UUID(), nullable=True),
    sa.Column('upload_proof', sa.Boolean(), nullable=True),
    sa.Column('certification_proof', sa.Boolean(), nullable=True),
    sa.Column('cl_status', postgresql.ENUM('INCOMPLETE', 'COMPLETED', name='processstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['moc_id'], ['MocTable.moc_id'], ),
    sa.PrimaryKeyConstraint('cl_id')
    )
    op.create_index(op.f('ix_ContinuousLearningTable_cl_id'), 'ContinuousLearningTable', ['cl_id'], unique=False)
    op.create_table('LicensureTable',
    sa.Column('licensure_id', sa.UUID(), nullable=False),
    sa.Column('moc_id', sa.UUID(), nullable=True),
    sa.Column('upload_license', sa.Boolean(), nullable=True),
    sa.Column('upload_moc', sa.Boolean(), nullable=True),
    sa.Column('upload_marksheet', sa.Boolean(), nullable=True),
    sa.Column('licensure_status', postgresql.ENUM('INCOMPLETE', 'COMPLETED', name='processstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['moc_id'], ['MocTable.moc_id'], ),
    sa.PrimaryKeyConstraint('licensure_id')
    )
    op.create_index(op.f('ix_LicensureTable_licensure_id'), 'LicensureTable', ['licensure_id'], unique=False)
    op.create_table('PaymentTable',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('moc_id', sa.UUID(), nullable=True),
    sa.Column('portal_payment_status', sa.Boolean(), nullable=True),
    sa.Column('examination_payment_status', sa.Boolean(), nullable=True),
    sa.Column('certificate_payment_status', sa.Boolean(), nullable=True),
    sa.Column('payment_status', postgresql.ENUM('INCOMPLETE', 'COMPLETED', name='processstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['moc_id'], ['MocTable.moc_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_PaymentTable_payment_id'), 'PaymentTable', ['payment_id'], unique=False)
    op.drop_table('UserRole_Table')
    op.drop_index(op.f('ix_User_Table_user_email'), table_name='User_Table')
    op.drop_table('User_Table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_Table',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_title', postgresql.ENUM('Mr', 'Ms', 'Dr', 'Mrs', name='usertitle', create_type=False), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_certificate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_passing_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_degree', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('User_Table_pkey'))
    )
    op.create_index(op.f('ix_User_Table_user_email'), 'User_Table', ['user_email'], unique=False)
    op.create_table('UserRole_Table',
    sa.Column('userrole_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_role', postgresql.ENUM('ADMIN', 'SUPERADMIN', 'USER', 'CANDIDATE', 'DIPLOMATE', name='userrole', create_type=False), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User_Table.user_id'], name=op.f('UserRole_Table_user_id_fkey')),
    sa.PrimaryKeyConstraint('userrole_id', name=op.f('UserRole_Table_pkey'))
    )
    op.drop_index(op.f('ix_PaymentTable_payment_id'), table_name='PaymentTable')
    op.drop_table('PaymentTable')
    op.drop_index(op.f('ix_LicensureTable_licensure_id'), table_name='LicensureTable')
    op.drop_table('LicensureTable')
    op.drop_index(op.f('ix_ContinuousLearningTable_cl_id'), table_name='ContinuousLearningTable')
    op.drop_table('ContinuousLearningTable')
    op.drop_table('UserExaminationSlotTable')
    op.drop_index(op.f('ix_MocTable_moc_id'), table_name='MocTable')
    op.drop_table('MocTable')
    op.drop_table('UserRoleTable')
    op.drop_table('ExaminationSlotTable')
    op.drop_index(op.f('ix_CycleTable_start_date'), table_name='CycleTable')
    op.drop_index(op.f('ix_CycleTable_end_date'), table_name='CycleTable')
    op.drop_index(op.f('ix_CycleTable_cycle_id'), table_name='CycleTable')
    op.drop_table('CycleTable')
    op.drop_index(op.f('ix_CertificationTable_user_id'), table_name='CertificationTable')
    op.drop_index(op.f('ix_CertificationTable_certification_id'), table_name='CertificationTable')
    op.drop_table('CertificationTable')
    op.drop_index(op.f('ix_UserTable_user_email'), table_name='UserTable')
    op.drop_table('UserTable')
    op.drop_index(op.f('ix_ExaminationTable_examination_id'), table_name='ExaminationTable')
    op.drop_index(op.f('ix_ExaminationTable_examination_date'), table_name='ExaminationTable')
    op.drop_index(op.f('ix_ExaminationTable_created_by'), table_name='ExaminationTable')
    op.drop_table('ExaminationTable')
    sa.Enum('ACTIVE', 'INACTIVE', 'LOST', name='certificationstatus').drop(op.get_bind())
    sa.Enum('INCOMPLETE', 'COMPLETED', name='processstatus').drop(op.get_bind())
    sa.Enum('ASSESMENT', 'REASSESMENT', name='examinationtype').drop(op.get_bind())
    sa.Enum('PENDING', 'SCHEDULED', 'COMPLETED', name='userexaminationstatus').drop(op.get_bind())
    sa.Enum('COMPLETED', 'PENDING', 'REFUNDED', name='paymentstatus').drop(op.get_bind())
    sa.Enum('INCOMPLETE', 'PUNCTUAL', 'DELAYED', 'DANGEROUSLY_DELAYED', name='mocstatus').drop(op.get_bind())
    # ### end Alembic commands ###
