"""Made The Degree Changes in the User Table

Revision ID: 31380b5e48a7
Revises: 2aa97f43a5b7
Create Date: 2026-05-20 11:56:40.687173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31380b5e48a7'
down_revision: Union[str, Sequence[str], None] = '2aa97f43a5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_Table', sa.Column('user_degree', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User_Table', 'user_degree')
    # ### end Alembic commands ###
