"""Made some minor Modifications in User Table

Revision ID: 4776bcc01771
Revises: 31380b5e48a7
Create Date: 2026-05-20 14:48:17.442269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4776bcc01771'
down_revision: Union[str, Sequence[str], None] = '31380b5e48a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User_Table', 'user_degree',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User_Table', 'user_degree',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
