"""UserRole Table Created

Revision ID: a10512e7f59f
Revises: fa3078ea0815
Create Date: 2026-05-19 15:27:06.383590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10512e7f59f'
down_revision: Union[str, Sequence[str], None] = 'fa3078ea0815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserRole_Table',
    sa.Column('userrole_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_role', sa.Enum('ADMIN', 'SUPERADMIN', 'USER', 'CANDIDATE', 'DIPLOMATE', name='userrole'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User_Table.user_id'], ),
    sa.PrimaryKeyConstraint('userrole_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserRole_Table')
    # ### end Alembic commands ###
